#!/bin/bash

DATE=`date`

cat > com/fluendo/player/Configure.java <<EOF
package com.fluendo.player;

class Configure
{
  public String buildInfo = "I was built on $DATE. $*";

  public Configure() {
  }
}
EOF
